version: "3.3"
networks:
  web:
    external: true
services:
  rigami-backend:
    build: .
    restart: unless-stopped
    environment:
      - DATABASE_USER
      - DATABASE_PASSWORD
      - DATABASE_HOST
      - JWT_SECRET_KEY
    extra_hosts:
      - "database:151.248.112.166"
    networks:
      - web
    volumes:
      - /data/rigami-icons-cache/:/icons-cache/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rigami-backend.rule=Host(`api.rigami.io`) && PathPrefix(`/v1`)"
      - "traefik.http.routers.rigami-backend.entrypoints=web-http,web-https"
      - "traefik.http.routers.rigami-backend.tls=true"
      - "traefik.http.routers.rigami-backend.tls.certresolver=letsEncrypt"
      - "traefik.http.services.rigami-backend-service.loadbalancer.server.port=8080"
